version: "3"

services:
  lb:
    build: ./
    container_name: go-lb
    ports:
      - "3030:3030"
    environment:
      - BACKENDS_LIST=http://web1:80,http://web2:80,http://web3:80
      - LB_PORT=3030
  web1:
    image: strm/helloworld-http
  web2:
    image: strm/helloworld-http
  web3:
    image: strm/helloworld-http
